import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { Salary } from '../../interfaces/Salary';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-inquiry-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './inquiry-form.html',
  styleUrl: './inquiry-form.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InquiryForm {
  selectedArea = signal<string | null>(null);
  selectedLocation = signal<string | null>(null);
  selectedPosition = signal<string | null>(null);
  selectedExperienceLevel = signal<string | null>(null);
  enteredSalary = signal<number | null>(null);

  work_fields = [
    'Engineering',
    'Marketing',
    'Sales',
    'Human Resources',
    'Finance',
    'Customer Support',
    'Product Management',
    'Design',
    'Operations',
    'IT',
  ];

  experience_levels = [
    'Junior',
    'Semi Senior',
    'Senior',
    'Executive',
  ];

  locations = [
    'USA',
    'UK',
    'Germany',
    'Japan',
    'Australia',
    'Canada',
    'Remote',
  ];

  positions = [
    'Software Engineer',
    'Product Manager',
    'Data Scientist',
    'UX Designer',
    'Sales Executive',
    'Marketing Specialist',
    'HR Manager',
    'Finance Analyst',
    'Customer Support Representative',
    'Operations Coordinator',
  ];

  submitForm() {
    const formData: Salary = {
      id: 0, // This would typically be generated by the backend
      area: this.selectedArea() ? this.selectedArea() : '',
      location: this.selectedLocation() ? this.selectedLocation() : '',
      position: this.selectedPosition() ? this.selectedPosition() : '',
      experienceLevel: this.selectedExperienceLevel() ? this.selectedExperienceLevel() : '',
      salary: this.enteredSalary() || 0,
    };
    console.log('Form submitted', formData);
  }

}
